name: Compile sanity check
on:
  push:
    branches:
    - master
    paths:
    - '**.tex'
    - '**.m4'
    - '**.sty'
    - Makefile
    - .github/workflows/compile.yml
    - 'img/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the system
      run: sudo apt-get -qq update
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        path: master
    - name: Checkout src repo
      uses: actions/checkout@v4
      with:
        repository: devnull-cz/unix-linux-prog-in-c-src
        path: unix-linux-prog-in-c-src
    - name: Install pre-requisites for LaTeX
      working-directory: master
      run: ./dev/install-latex.sh
    - name: Install pre-requisites for spell check
      working-directory: master
      run: ./dev/install-spellcheck.sh
    - name: Check labels
      working-directory: master
      run: ./dev/check-label.sh
    - name: Run spellcheck
      working-directory: master
      run: make spellcheck
    - name: Compile
      working-directory: master
      run: make slides notes
    - name: Check example links
      working-directory: master
      run: ./dev/check-examples.sh
