name: Create release with PDFs
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the system
      run: sudo apt-get -qq update
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
    - name: Install pre-requisites for LaTeX
      working-directory: master
      run: ./dev/install-latex.sh
    - name: Compile first phase
      working-directory: master
      run: make slides notes
    - name: Compile second phase to get table of contents
      working-directory: master
      run: make slides notes
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        draft: false
        files: |
          ./master/unix-linux-prog-in-c.pdf
          ./master/unix-linux-prog-in-c_slides-only.pdf
