name: Create release with PDFs
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the system
      run: sudo apt-get -qq update
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
    - name: Install pre-requisites for LaTeX
      working-directory: master
      run: ./dev/install-latex.sh
    - name: Compile first phase
      working-directory: master
      run: make slides notes
    - name: Compile second phase to get table of contents
      working-directory: master
      run: make slides notes
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload PDF
      id: upload-release-asset
      uses: alexellis/upload-assets@0.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: '["./master/unix-linux-prog-in-c.pdf", "unix-linux-prog-in-c_slides-only.pdf"]'
