name: Compile
on:
  push:
    branches:
    - master
    paths:
    - *.tex
    - *.m4
    - *.sty
    - Makefile
    - .github/workflows/pdfs.yml
    - img/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the system
      run: sudo apt-get -qq update
    - name: Install pre-requisites for LaTeX
      sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-pstricks aspell aspell-en
    - name: Run spellcheck
      run: make spellcheck
    - name: Compile first phase
      run: make slides notes
    - name: Compile second phase to get table of contents
      run: make slides notes
