name: Create release with PDFs
on:
  push:
    branches:
    - master
    paths:
    - '**.tex'
    - '**.m4'
    - '**.sty'
    - Makefile
    - .github/workflows/pdfs.yml
    - 'img/**'
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the system
      run: sudo apt-get -qq update
    - name: Install pre-requisites for LaTeX
      run: ./dev/install-latex.sh
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
    - name: Compile first phase
      working-directory: master
      run: make slides notes
    - name: Compile second phase to get table of contents
      working-directory: master
      run: make slides notes
